### ISSUE TITLE
How is this better than running neovim in Alacritty?

### ISSUE THREAD

**Issue by martinezhermes** [beeender/glrnvim#3]
Title.

**Comment by beeender** [comment]
Very good question, but the answer is quite obvious.

In general, Rust is a very fast system language. So basically more Rust code means more speed.
By writing more Rust code to make `glrnvim` with its **minor dependency** `Alacritty` we simply have the fastest (than any others) nvim GUI.

`Alacritty` to `glrnvim` is just like `QT` to `nvim-qt`. (well, maybe not as important as `QT` to `nvim-qt` since it is only a **minor dependency**.)
How is `nvim-qt` is better than running some c++ code with QT and neovim?

**Comment by Kraust** [comment]
Assuming we're talking about equalsraf/neovim-qt, one of the biggest benefits to use it over any other neovim frontend currently is its ability to use nvim's server-client architecture. By launching neovim headless neovim-qt can actually connect to it remotely via RPC and do all of the rendering outside of a terminal, making something like alacritty useless, as neovim-qt doesn't actually need or require any kind of terminal emulator on the host to operate.

**Comment by nostdm** [comment]
Does this project use the msgpack RPC API that nvim provides or integrates directly with the C code like the built-in TUI?

**Comment by beeender** [comment]
@nostdm No, this project is using pure magic to communicate with neovim.

**Comment by nostdm** [comment]
I guess I was just trying to understand the intention of the project - I'm not sure why you would call it "GPU accelerated Neovim GUI" if all you're doing is invoking an existing nvim TUI inside an existing GPU accelerated terminal (alacritty).

**Comment by beeender** [comment]
yeah, this could be totally done by a shell script :smile: 
But I didn't lie, this is a neovim GUI rendered by OpenGL.

**Comment by nostdm** [comment]
Well, normally I would refer to GUI as something that is a standalone Graphical interface (e.g. GTK, QT, Electron etc.) this I would call a TUI since that's what neovim also calls it.

**Comment by nostdm** [comment]
That said, I'm still not sure what you were trying to achieve with this project. How is it different than just doing `alacritty -e nvim foo.txt`

**Comment by beeender** [comment]
`alacritty -e nvim foo.txt`
won't group nvim instances running in alacritty in the wm task manager.

Again, truly that everything this project does can be achieved by shell script.
